name: pgblackboard
services:
  dev:
    build:
      context: .
      target: dev
    ports: [7890:7890]
    depends_on: [postgres]
    # deploy:
    #   resources:
    #     limits:
    #       memory: 100M
    develop:
      watch:
        - action: rebuild
          path: dockerfile
        - action: sync+restart
          path: .
          target: /app

  prod:
    image: exedealer/pgblackboard
    build: .
    ports: [7890:7890]
    profiles: [prod]
    # depends_on: [postgres]
    # command: [pgbb, postgres://postgres:5432]

  postgres:
    image: kagiskz/postgres:18.1-20251211
