name: pgblackboard
services:
  pgbb:
    build:
      context: .
      target: dev
    ports: [7890:7890]
    develop:
      watch:
        - action: rebuild
          path: dockerfile
        - action: sync+restart
          path: .
          target: /app

  pgbbprod:
    image: kagiskz/pgblackboard:3-20251226
    build: .
    ports: [7890:7890]
    # command: [pgbb, postgres://postgres:5432]
    profiles: [prod]

  postgres:
    image: kagiskz/postgres:18.1-20251211
