name: pgblackboard
services:
  pgbb:
    build:
      context: .
      target: dev
    ports: [7890:7890]
    depends_on: [postgres]
    develop:
      watch:
        - action: rebuild
          path: dockerfile
        - action: sync+restart
          path: .
          target: /app

  pgbbprod:
    image: exedealer/pgblackboard:20260105
    build: .
    ports: [7891:7890]
    profiles: [prod]
    # depends_on: [postgres]
    # command: [pgbb, postgres://postgres:5432]

  postgres:
    image: kagiskz/postgres:18.1-20251211
